runtime: nodejs10

default_expiration: "0s"

handlers:
 - url: /
   static_files: build/index.html
   upload: build/index.html

 - url: /static
   static_dir: build/static
   expiration: "365d"

 - url: /
   static_dir: build
